### ISSUE TITLE
Release blocker: entity_access() checks are failing

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/field_collection#8] opened 2022-04-14 23:22 UTC
I have a Drupal 7 site, upgrade to Backdrop. Field collections on nodes are showing the "Edit" and "Delete" links even for anonymous viewers. 

There is a call to `entity_access()` around the generation of those links, but it always returns TRUE:
```php
          foreach (field_collection_get_operations($settings) as $op => $label) {
            if ($settings[$op] && entity_access($op === 'edit' ? 'update' : $op, 'field_collection_item', $field_collection)) {
              $links['#links'][$op] = array(
                // entity_i18n_string() is from the D7 Entity API module.
                // 'title' => entity_i18n_string("field:{$field['field_name']}:{$instance['bundle']}:setting_$op", $settings[$op]),
                'title' => $settings[$op],
                'href' => $field_collection->path() . '/' . $op,
                'query' => backdrop_get_destination(),
              );
            }
          }
```

**Comment by jenlampton** [comment] 2022-04-14 23:39
I've fixed this for my site by ading a user_access check around those links, and removing them if access is denied:

```php
/**
 * Prepare vairables for field templates.
 *
 * @see  field.tpl.php and derivatives.
 */
function leap_preprocess_field(&$variables) {
  $element = $variables['element']; // Nice shorthand.
  if ($element['#field_name'] == 'field_whateveryournameis') {
    if (!user_access('edit field collections')) {
      foreach ($variables['items'] as $delta => $item) {
        unset($variables['items'][$delta]['links']);
      }
    }
  }
}
```

**Comment by jenlampton** [comment] 2022-04-20 21:39
Pushing a PR that adds an `access()` method onto the `FieldCollectionItemEntity` entity.

**Comment by oadaeh** [comment] 2022-05-12 13:35
Sorry for the long delay. I've been rather busy with work and personal life lately.

I took a look at this a week or two ago, and I think the code is not quite right for this module, but I'm not yet 100% sure. There is already an [access function](https://github.com/backdrop-contrib/field_collection/blob/211f9fee57cc8c1fedb745219f72148e5cc9c448/field_collection.module#L367) in the module, and it's specified in the [entity info hook](https://github.com/backdrop-contrib/field_collection/blob/211f9fee57cc8c1fedb745219f72148e5cc9c448/field_collection.module#L83) (though none of the menu items use it). When I tried to verify its use to see if it should be the content in the access() method, I found it never got called.

So, I started investigating that and ended up examining the content of the entity info hook function and found that it needed to be modified. While examining that function, I went down a rabbit hole of trying to verify what could and should be there and what could and should not be there, based on differences between Backdrop & the Entity Plus module from Drupal & the Entity API module. While doing that, I found some code that was different from what was documented, and so I felt I needed to resolve that before I could move on, but I never got to the end of that before I ran out of time.

I feel like I need to resolve and fix the entity info hook function before I can get back on this, so that's going to be my first priority, and so I created a ticket for it: #10.

**Comment by oadaeh** [comment] 2022-07-11 17:59
I finally got back to this (and #10) and determined why things I thought were working were not actually working or not working the way I thought they were, and determined that your approach was the correct way to do it, but I used the contents of the existing field_collection_item_access() function instead, since that was designed for this module and wasn't a generic catch all function. Let me know if that works for you or not.

**Comment by laryn** [comment] 2023-01-19 16:58
@jenlampton Not sure if you saw the comment above but I think that was for you. ☝️ 

(I am not actively using this module, just scoping it out for a potential project)

**Comment by herbdool** [comment] 2023-07-26 14:50
I think this now works as expected. The edit, delete links don't show up for anonymous. The logic looks the same as before so it should be backwards-compatible.

**Comment by oadaeh** [comment] 2024-01-11 23:42
I'm closing this as fixed.

**Closed as completed by oadaeh** 2024-01-11 23:42 UTC
Labels: status - fixed
